spring:
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
                    lower-case-service-id: true
            routes:
                - id: auth-service
                  uri: lb://realtime-chatapp-auth-service
                  predicates:
                      - Path=/auth/**
                  filters:
                      - StripPrefix=1
                - id: user-service
                  uri: lb://realtime-chatapp-user-service
                  predicates:
                      - Path=/users/**
                  filters:
                      - StripPrefix=1
                - id: chat-service
                  uri: lb://realtime-chatapp-message-service
                  predicates:
                      - Path=/chat/**
                  filters:
                      - StripPrefix=1
            globalcors:
                add-to-simple-url-handler-mapping: true
                corsConfigurations:
                    "[/**]":
                        allowedOriginPatterns: "*"
                        allowedMethods:
                            - GET
                            - POST
                            - PUT
                            - PATCH
                            - DELETE
                            - OPTIONS
                        allowedHeaders:
                            - "*"
                        allowCredentials: true

logging:
    level:
        org.springframework.cloud.gateway.filter: DEBUG
        org.springframework.cloud.gateway.handler: DEBUG
